# Generated by Django 4.2.16 on 2024-10-12 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="store.customer",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="delivery_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="payment_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="placed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
