# Generated by Django 4.2.16 on 2024-10-18 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_orderitem_unit_price_cart_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="numerical_barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
