# Generated by Django 4.2.16 on 2024-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="preference",
            field=models.CharField(
                choices=[
                    ("high", "High Priority"),
                    ("medium", "Medium Priority"),
                    ("low", "Low Priority"),
                ],
                max_length=18,
            ),
        ),
    ]
