# Generated by Django 4.2.15 on 2024-08-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_location_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="restock_value",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.order",
            ),
        ),
    ]
