# Generated by Django 4.2.16 on 2024-10-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_numerical_barcode_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="serial_number",
        ),
        migrations.CreateModel(
            name="ProductInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=30, unique=True)),
                ("sku", models.CharField(max_length=30)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
