# Generated by Django 4.2.15 on 2024-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_restock_value_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
