# Generated by Django 4.2.16 on 2024-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_vendor_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("computers", "Computers"),
                    ("networking", "Networking"),
                    ("electrical", "Electrical"),
                ],
                default="computers",
                max_length=18,
            ),
        ),
    ]
