# Generated by Django 4.2.16 on 2024-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_country_code_product_manufacturer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
