# Generated by Django 4.2.16 on 2024-10-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productinstance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
