# Generated by Django 4.2.16 on 2024-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_model_number_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
