# Generated by Django 4.2.16 on 2024-10-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="promotions",
        ),
    ]
