# Generated by Django 4.2.16 on 2024-10-27 08:53

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_remove_product_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="productinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "Out on Loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="a",
                help_text="Book Availability",
                max_length=1,
            ),
        ),
    ]
