# Generated by Django 4.2.16 on 2024-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "Out on Loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="a",
                help_text="Product Availability",
                max_length=1,
            ),
        ),
    ]
