# Generated by Django 4.2.16 on 2024-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_country_code_product_manufacturer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
