# Generated by Django 4.2.6 on 2023-10-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
