# Generated by Django 4.2.15 on 2024-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
