# Generated by Django 4.2.15 on 2024-08-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_product_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="expiry_date",
        ),
    ]
